# Generated by Django 5.0.3 on 2024-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
