# Generated by Django 5.0.3 on 2024-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
