# Generated by Django 5.0.3 on 2024-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0005_booking_book_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
