# Generated by Django 5.0.3 on 2024-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsiruser', '0006_remove_profile_debt_remove_profile_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.CharField(max_length=266, null=True),
        ),
    ]
